version: "3.9"
services:
  api:
    build: ./api
    container_name: dockerapi_container
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
  blog:
    build: ./blog
    container_name: blog_container
    ports:
      - '3000:3000'
    volumes:
      - ./blog:/app
      - ./api/node_modules:/app/node_modules
    stdin_open: true
    tty: true
